version: '2.0'

services:
     frontend:
       image: hackathon-frontend
       ports:
         - 8080:3000
       links:
         - backend
         - mongodb
     backend:
       image: hackathon-backend
       environment:
          - MONGO_CONN_STRING=mongodb://mongodb:27017
       ports:
         - 8081:3000
         - 8082:1337
       links:
         - mongodb
     mongodb:
       image: mongo
       volumes:
         - /mnt/mongobkup:/data/db
         - /mnt/mongobkup:/data/configdb
       ports:
         - 27017:27017
